# Generated by Django 6.1.1 on 2026-09-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_options_alter_doctor_created_at_and_more'),
        ('mappings', '0001_initial'),
        ('patients', '0002_alter_patient_options_alter_patient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdoctormapping',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='patientdoctormapping',
            index=models.Index(fields=['patient', 'doctor'], name='mappings_pa_patient_334947_idx'),
        ),
        migrations.AddIndex(
            model_name='patientdoctormapping',
            index=models.Index(fields=['-assigned_at'], name='mappings_pa_assigne_fec9e3_idx'),
        ),
    ]
