# Generated by Django 6.1.1 on 2026-09-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialization', 'is_active'], name='doctors_doc_special_78e3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['name', 'specialization'], name='doctors_doc_name_727299_idx'),
        ),
    ]
